# Generated by Django 5.2.4 on 2025-09-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter product name...', max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='brief description of the product..', max_length=100)),
                ('description', models.TextField(blank=True, help_text='describe the product..', max_length=700)),
                ('additional_info', models.TextField(blank=True, help_text='additional info of the product..', max_length=1000)),
                ('product_image1', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('product_image2', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('product_image3', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('product_image4', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('new_since', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
