# Generated by Django 6.1 on 2026-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="new_since",
        ),
        migrations.RemoveField(
            model_name="product",
            name="previous_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_end",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale_start",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
