# Generated by Django 6.1 on 2026-08-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_current_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_title",
        ),
    ]
